repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-json
    -   id: debug-statements

-   repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
    -   id: flake8
        additional_dependencies:
        -   flake8-docstrings
        -   flake8-import-order
        -   flake8-bugbear
        -   flake8-comprehensions
        -   flake8-return

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1
    hooks:
    -   id: mypy
        additional_dependencies:
        -   types-requests==2.31.0.2
        -   types-tabulate==0.9.0.3
        -   types-beautifulsoup4==4.12.0.5
