# Default language version for all hooks
default_language_version:
    python: python3

# Global options for all hooks
default_stages: [pre-commit]

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
        args: ['--maxkb=500']
    -   id: check-json
    -   id: debug-statements

-   repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
    -   id: black
        language_version: python3

-   repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
    -   id: flake8
        # Run only on changed files for faster execution
        additional_dependencies:
        -   flake8-docstrings
        -   flake8-import-order
        -   flake8-bugbear
        -   flake8-comprehensions
        -   flake8-return

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1
    hooks:
    -   id: mypy
        exclude: ^tests/
        # Use stricter type checking to catch more errors
        args: [
            --config-file=mypy.ini,
            --strict-equality,
            --disallow-any-generics,
            --disallow-subclassing-any,
            --no-implicit-optional,
            --warn-redundant-casts,
            --warn-unused-ignores,
            --warn-return-any,
            --warn-unreachable,
        ]
        additional_dependencies:
        -   types-requests==2.31.0.2
        -   types-tabulate==0.9.0.3
        -   types-beautifulsoup4==4.12.0.5

-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        args: [--profile=black, --filter-files]

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.6
    hooks:
    -   id: ruff
        args: [--fix]
    -   id: ruff-format
