name: Code Style Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  style-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black isort flake8 flake8-docstrings flake8-import-order flake8-bugbear flake8-comprehensions flake8-return mypy ruff

    - name: Run black
      run: python -m black --check .

    - name: Run isort
      run: python -m isort --check .

    - name: Run flake8
      run: python -m flake8 .

    - name: Run ruff
      run: python -m ruff check .

    - name: Run mypy
      run: python -m mypy .
