name: Test Workflow

on:
  workflow_dispatch:  # Allow manual triggering

jobs:
  test-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Test workflow step
        run: echo "This is a test workflow to verify GitHub Actions is working correctly."
